import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

import { compileFromFile } from 'json-schema-to-typescript';

const check = process.argv.includes('--check');
const uiRoot = process.cwd();
const repoRoot = resolve(uiRoot, '..');
const generatedDir = resolve(uiRoot, 'src/lib/generated');
const schemaPath = join(generatedDir, 'codeview.schema.json');
const typesPath = join(generatedDir, 'codeview-schema.d.ts');

function generateSchema(out: string): void {
	mkdirSync(dirname(out), { recursive: true });
	execFileSync(
		'cargo',
		[
			'run',
			'--quiet',
			'--manifest-path',
			join(repoRoot, 'Cargo.toml'),
			'-p',
			'codeview-cli',
			'--',
			'schema',
			'--out',
			out,
		],
		{ stdio: 'inherit', cwd: repoRoot },
	);
}

async function generateTypes(schema: string): Promise<string> {
	return compileFromFile(schema, {
		additionalProperties: false,
		bannerComment:
			'/* This file is generated by scripts/generate-schema.ts. Do not edit by hand. */',
		declareExternallyReferenced: true,
		enableConstEnums: false,
		style: {
			printWidth: 100,
			singleQuote: true,
			trailingComma: 'all',
			useTabs: true,
		},
	});
}

function assertCurrent(path: string, expected: string): void {
	if (!existsSync(path)) {
		console.error(`Generated file is missing: ${path}`);
		process.exitCode = 1;
		return;
	}
	const current = readFileSync(path, 'utf8');
	if (current !== expected) {
		console.error(`Generated file is stale: ${path}`);
		process.exitCode = 1;
	}
}

if (check) {
	const tempDir = join(tmpdir(), `codeview-schema-${process.pid}`);
	const tempSchemaPath = join(tempDir, 'codeview.schema.json');
	try {
		generateSchema(tempSchemaPath);
		const types = await generateTypes(tempSchemaPath);
		assertCurrent(schemaPath, readFileSync(tempSchemaPath, 'utf8'));
		assertCurrent(typesPath, types);
	} finally {
		rmSync(tempDir, { force: true, recursive: true });
	}

	if (process.exitCode) {
		console.error('Run `vp run schema:generate` from codeview-ui to refresh generated types.');
	}
} else {
	generateSchema(schemaPath);
	const types = await generateTypes(schemaPath);
	writeFileSync(typesPath, types);
}
