import { Result } from 'better-result';
import type { RequestEvent } from '@sveltejs/kit';
import type { Confidence, CrateGraph, EdgeKind, Node, Edge, NodeKind, Visibility, Workspace } from '$lib/graph';
import type { CrateIndex, CrateTree, NodeDetail } from '$lib/schema';
import { parseWorkspace } from '$lib/schema';
import { isStdCrate, isRustChannel } from '$lib/std';
import type { CrossEdgeData, DataProvider } from '../provider';
import type { GraphStore } from '$cloudflare/store';
import type { CrateRegistry } from '$cloudflare/registry';
import type { Ecosystem } from '../registry/types';
import { getRegistry } from '../registry/index';
import { fetchSourceFileFromArchive } from '../parser/archive';
import { getSourceAdapter } from '../sources/index';
import { fetchSourcesWithProviders } from '../sources/runner';
import { ValidationError, NotAvailableError, RateLimitError } from '../errors';
import { checkRateLimitPolicy } from './ratelimit';
import { isValidCrateName, isValidVersion, crateNameVariants, normalizeCrateName } from '../validation';
import { getLogger } from '$lib/log';
import { USER_AGENT, SOURCE_MAX_BYTES, resolveSourceFileFromMap, selectSourceProviders, classifyStatusAction } from '../provider-utils';

const log = getLogger('cloudflare');

/** Get a GraphStore stub for a specific crate */
function getCrateGraphStore(env: AppEnv, name: string, version: string): DurableObjectStub<GraphStore> {
	return env.GRAPH_STORE.get(env.GRAPH_STORE.idFromName(`rust/${name}/${version}`));
}

/**
 * Narrows the global Env (generated by `wrangler types`) with typed DO/Workflow
 * generics and optional secrets that aren't declared in wrangler.toml.
 */
type AppEnv = Omit<Env, 'GRAPH_STORE' | 'CRATE_REGISTRY' | 'PARSE_CRATE'> & {
	GRAPH_STORE: DurableObjectNamespace<GraphStore>;
	CRATE_REGISTRY: DurableObjectNamespace<CrateRegistry>;
	PARSE_CRATE: Workflow<{ ecosystem: Ecosystem; name: string; version: string }>;
	GITHUB_REPO?: string;
	GITHUB_REF?: string;
	GITHUB_TOKEN?: string;
};

async function resolveStdVersion(
	r2: R2Bucket, name: string, version: string
): Promise<string | null> {
	if (!isStdCrate(name) || !isRustChannel(version)) return version;
	const obj = await r2.get(`rust/${name}/${version}.json`);
	if (!obj) return null;
	const pointer = await obj.json<{ version: string }>();
	return pointer.version ?? null;
}

export function createCloudflareProvider(env: AppEnv, event?: RequestEvent): DataProvider {
	const registryStub = env.CRATE_REGISTRY.get(env.CRATE_REGISTRY.idFromName('global'));
	const sourceFileCache = new Map<string, string>();
	const SOURCE_FILE_CACHE_MAX = 512;

	function sourceCacheKey(
		crateName: string,
		crateVersion: string,
		file: string,
		sourceProvider: 'auto' | 'crates-io' | 'github'
	): string {
		return `${crateName}|${crateVersion}|${sourceProvider}|${file}`;
	}

	function getCachedSourceFile(key: string): string | null {
		const value = sourceFileCache.get(key);
		if (value === undefined) return null;
		sourceFileCache.delete(key);
		sourceFileCache.set(key, value);
		return value;
	}

	function setCachedSourceFile(key: string, content: string): void {
		if (sourceFileCache.has(key)) sourceFileCache.delete(key);
		sourceFileCache.set(key, content);
		while (sourceFileCache.size > SOURCE_FILE_CACHE_MAX) {
			const oldestKey = sourceFileCache.keys().next().value;
			if (oldestKey === undefined) break;
			sourceFileCache.delete(oldestKey);
		}
	}

	return {
		async loadWorkspace() {
			// Workspace is not used in hosted mode - return null
			return null;
		},

		async loadSourceFile(
			relativePath: string,
			crateName?: string,
			crateVersion?: string,
			sourceProvider: 'auto' | 'crates-io' | 'github' = 'auto'
		) {
			// Get crate-specific GraphStore if available
			const graphStub = crateName && crateVersion
				? getCrateGraphStore(env, crateName, crateVersion)
				: env.GRAPH_STORE.get(env.GRAPH_STORE.idFromName('default'));

			// Check DO cache first
			const cachedFile = await graphStub.getSourceFile(relativePath);
			if (cachedFile) return { error: null, content: cachedFile };

			if (!crateName || !crateVersion) {
				return { error: 'Source file not available', content: null };
			}

			const cacheKey = sourceCacheKey(crateName, crateVersion, relativePath, sourceProvider);
			const cachedContent = getCachedSourceFile(cacheKey);
			if (cachedContent !== null) {
				return { error: null, content: cachedContent };
			}

			const sourceAdapterResult = getSourceAdapter('rust');
			if (sourceAdapterResult.isErr()) {
				return { error: sourceAdapterResult.error.message, content: null };
			}

			const registryResult = getRegistry('rust');
			if (registryResult.isErr()) {
				return { error: registryResult.error.message, content: null };
			}

			let metadata: Awaited<ReturnType<typeof registryResult.value.resolve>> | null = null;
			for (const variant of crateNameVariants(crateName)) {
				const resolved = await registryResult.value.resolve(variant, crateVersion);
				if (resolved) {
					metadata = resolved;
					break;
				}
			}
			if (!metadata) {
				return { error: 'Source metadata unavailable', content: null };
			}

			if ((sourceProvider === 'auto' || sourceProvider === 'crates-io') && metadata.sourceArchiveUrl) {
				const direct = await fetchSourceFileFromArchive(metadata.sourceArchiveUrl, relativePath, {
					maxBytes: SOURCE_MAX_BYTES,
					userAgent: USER_AGENT
				});
				if (direct.status === 'ok') {
					setCachedSourceFile(cacheKey, direct.content);
					return { error: null, content: direct.content };
				}
				if (sourceProvider === 'crates-io') {
					return { error: direct.status === 'error' ? direct.message : 'Source file not available', content: null };
				}
			}

			const providers = sourceAdapterResult.value.getProviders({
				ecosystem: 'rust',
				name: metadata.name,
				version: metadata.version,
				metadata
			});
			const selectedProviders = selectSourceProviders(providers, sourceProvider);
			const files = await fetchSourcesWithProviders(
				selectedProviders,
				{ ecosystem: 'rust', name: metadata.name, version: metadata.version, metadata },
				{
					maxBytes: SOURCE_MAX_BYTES,
					userAgent: USER_AGENT,
					githubToken: env.GITHUB_TOKEN
				}
			);
			if (!files) {
				return { error: 'Source file not available', content: null };
			}

			const content = resolveSourceFileFromMap(files, relativePath);
			if (content === null) {
				return { error: 'File not found', content: null };
			}
			setCachedSourceFile(cacheKey, content);
			return { error: null, content };
		},

		async loadCrateGraph(name: string, version: string) {
			// Progressive storage: reconstruct graph from DO
			const resolved = await resolveStdVersion(env.CRATE_GRAPHS, name, version);
			if (!resolved) return null;

			const graphStub = getCrateGraphStore(env, name, resolved);
			const hasCrate = await graphStub.hasCrate('rust', name, resolved);
			if (!hasCrate) return null;

			// Reconstruct graph from nodes/edges
			const [nodes, edges] = await Promise.all([
				graphStub.getNodesForCrate('rust', name, resolved),
				graphStub.getEdgesForCrate('rust', name, resolved)
			]);

			const normalizedName = normalizeCrateName(name);
			return {
				id: normalizedName,
				name: normalizedName,
				version: resolved,
				nodes,
				edges
			} as CrateGraph;
		},

		async loadCrateTree(name: string, version: string): Promise<CrateTree | null> {
			const resolved = await resolveStdVersion(env.CRATE_GRAPHS, name, version);
			if (!resolved) {
				log.info`loadCrateTree(cf) name=${name} version=${version} resolved=none`;
				return null;
			}

			// Try R2 first (fast)
			const key = `rust/${name}/${resolved}/tree.json`;
			const obj = await env.CRATE_GRAPHS.get(key);
			if (obj) {
				const result = await Result.tryPromise(() => obj.json<CrateTree>());
				if (result.isOk()) {
					log.info`loadCrateTree(cf) source=r2 name=${name} version=${resolved} nodes=${result.value.nodes.length} edges=${result.value.edges.length}`;
					return result.value;
				}
				log.warn`loadCrateTree(cf) source=r2 parse-failed name=${name} version=${resolved}`;
			}

			// Fall back to DO
			const graphStub = getCrateGraphStore(env, name, resolved);
			const meta = await graphStub.getCrateMeta('rust', name, resolved);
			const treeJson = meta?.treeJson;
			if (!treeJson) {
				log.info`loadCrateTree(cf) source=do name=${name} version=${resolved} hit=no`;
				return null;
			}

			const result = Result.try(() => JSON.parse(treeJson) as CrateTree);
			if (result.isErr()) {
				log.error`Failed to parse crate tree from DO: ${result.error}`;
				return null;
			}
			log.info`loadCrateTree(cf) source=do name=${name} version=${resolved} nodes=${result.value.nodes.length} edges=${result.value.edges.length}`;
			return result.value;
		},

		async loadCrateIndex(name: string, version: string): Promise<CrateIndex | null> {
			const resolved = await resolveStdVersion(env.CRATE_GRAPHS, name, version);
			if (!resolved) return null;

			// Try R2 first (fast)
			const key = `rust/${name}/${resolved}/index.json`;
			const obj = await env.CRATE_GRAPHS.get(key);
			if (obj) {
				const result = await Result.tryPromise(() => obj.json<CrateIndex>());
				if (result.isOk()) return result.value;
			}

			// Fall back to DO
			const graphStub = getCrateGraphStore(env, name, resolved);
			const meta = await graphStub.getCrateMeta('rust', name, resolved);
			if (!meta?.indexJson) return null;

			const result = Result.try(() => JSON.parse(meta.indexJson) as CrateIndex);
			if (result.isErr()) {
				log.error`Failed to parse crate index from DO: ${result.error}`;
				return null;
			}
			return result.value;
		},

		async loadNodeDetail(name: string, version: string, nodeId: string): Promise<NodeDetail | null> {
			const resolved = await resolveStdVersion(env.CRATE_GRAPHS, name, version);
			if (!resolved) return null;

			const graphStub = getCrateGraphStore(env, name, resolved);

			// Load node and its edges concurrently
			const [node, nodeEdges] = await Promise.all([
				graphStub.getNode('rust', name, resolved, nodeId),
				graphStub.getEdgesForNode('rust', name, resolved, nodeId)
			]);

			if (!node) return null;

			// Collect all edges - start with direct edges
			const allEdges = [...nodeEdges];
			const edgeSet = new Set(nodeEdges.map(e => `${e.from}|${e.to}|${e.kind}`));

			// For types with impl blocks, follow Defines edges to get impl -> method edges
			// This enables showing methods in the detail view
			const isTypeNode = ['Struct', 'Enum', 'Union', 'Trait', 'TraitAlias', 'TypeAlias'].includes(node.kind);
			const implIds: string[] = [];
			if (isTypeNode) {
				for (const edge of nodeEdges) {
					if (edge.kind === 'Defines' && edge.from === nodeId) {
						implIds.push(edge.to);
					}
				}
			}

			// Load edges from impl blocks (to get Contains/Defines -> Function edges)
			if (implIds.length > 0) {
				const implEdgePromises = implIds.map(implId => 
					graphStub.getEdgesForNode('rust', name, resolved, implId)
				);
				const implEdgesArrays = await Promise.all(implEdgePromises);
				for (const implEdges of implEdgesArrays) {
					for (const edge of implEdges) {
						const key = `${edge.from}|${edge.to}|${edge.kind}`;
						if (!edgeSet.has(key)) {
							allEdges.push(edge);
							edgeSet.add(key);
						}
					}
				}
			}

			// Get related nodes (targets of all edges including impl methods)
			const relatedIds = new Set<string>();
			for (const edge of allEdges) {
				if (edge.from !== nodeId) relatedIds.add(edge.from);
				if (edge.to !== nodeId) relatedIds.add(edge.to);
			}

			// Load related nodes with full data
			const relatedNodes: Node[] = [];
			for (const id of relatedIds) {
				const related = await graphStub.getNode('rust', name, resolved, id);
				if (related) {
					relatedNodes.push(related as Node);
				}
			}

			return {
				node,
				edges: allEdges,
				relatedNodes
			};
		},

		async getCrossEdgeData(nodeId: string): Promise<CrossEdgeData> {
			const result = await registryStub.getCrossEdgeData('rust', nodeId);
			return {
				edges: result.edges.map((edge) => ({
					...edge,
					kind: edge.kind as EdgeKind,
					confidence: edge.confidence as Confidence
				})),
				nodes: result.nodes.map((node) => ({
					...node,
					kind: node.kind as NodeKind,
					visibility: node.visibility as Visibility
				}))
			};
		},

		async getCrateStatus(name: string, version: string) {
			// Std crates are pre-built via CI — check R2 directly instead of registry
			if (isStdCrate(name)) {
				const resolved = await resolveStdVersion(env.CRATE_GRAPHS, name, version);
				if (resolved) {
					const head = await env.CRATE_GRAPHS.head(`rust/${name}/${resolved}/graph.json`);
					if (head) return { status: 'ready' as const };
				}
				return {
					status: 'failed' as const,
					error: `Std crate ${name}@${version} not available. Pre-built graphs are generated via CI.`
				};
			}
			const current = await registryStub.getStatus('rust', name, version);
			// Registry status can lag/reset while graph data already exists.
			// Promote to ready and heal registry state from graph presence.
			if (current.status === 'unknown') {
				try {
					const graphStub = getCrateGraphStore(env, name, version);
					const hasGraph = await graphStub.hasCrate('rust', name, version);
					if (hasGraph) {
						await registryStub.setStatus('rust', name, version, 'ready');
						return { status: 'ready' as const };
					}
				} catch {}
			}
			// Auto-trigger parse for unknown crates
			if (current.status === 'unknown' && isValidCrateName(name) && isValidVersion(version)) {
				await Promise.all([
					registryStub.setStatus('rust', name, version, 'processing'),
					env.PARSE_CRATE.create({ params: { ecosystem: 'rust' as const, name, version } })
				]);
				return { status: 'processing' as const };
			}
			// Re-derive action from error message (not stored in DB)
			const action = classifyStatusAction(current);
			return action ? { ...current, action } : current;
		},

		async triggerParse(name: string, version: string, force?: boolean) {
			if (isStdCrate(name)) {
				return Result.err(new NotAvailableError({ message: `${name} is a standard library crate and cannot be parsed on-demand` }));
			}
			if (!isValidCrateName(name) || !isValidVersion(version)) {
				return Result.err(new ValidationError({ message: 'Invalid crate name or version' }));
			}

			if (event) {
				const allowed = await checkRateLimitPolicy(event, 'parse');
				if (!allowed) {
					return Result.err(new RateLimitError({ message: 'Rate limit exceeded' }));
				}
			}

			if (!force) {
				const current = await registryStub.getStatus('rust', name, version);
				if (current.status === 'processing' || current.status === 'ready') return Result.ok(undefined);
			}

			// Set status and trigger workflow concurrently
			await Promise.all([
				registryStub.setStatus('rust', name, version, 'processing'),
				env.PARSE_CRATE.create({ params: { ecosystem: 'rust', name, version } })
			]);
			return Result.ok(undefined);
		},

		async triggerStdInstall(_name: string, _version: string) {
			return Result.err(new NotAvailableError({ message: 'std crate installation is not available in hosted mode' }));
		},

		async searchRegistry(query: string) {
			const registryResult = getRegistry('rust');
			if (registryResult.isErr()) return [];
			const results = await registryResult.value.search(query);
			return results.map((r) => ({
				name: r.name,
				version: r.version,
				description: r.description
			}));
		},

		async getTopCrates(limit = 10) {
			const registryResult = getRegistry('rust');
			if (registryResult.isErr()) return [];
			const results = await registryResult.value.listTop(limit);
			return results.map((r) => ({
				name: r.name,
				version: r.version,
				description: r.description
			}));
		},

		async getProcessingCrates(limit = 20) {
			return await registryStub.getProcessingCrates('rust', limit);
		},


		async getCrateVersions(name: string, limit = 20): Promise<string[]> {
			if (isStdCrate(name)) {
				// Check all channels concurrently
				const channelNames = ['stable', 'nightly', 'beta'] as const;
				const results = await Promise.all(
					channelNames.map((ch) => env.CRATE_GRAPHS.head(`rust/${name}/${ch}.json`))
				);
				const channels = channelNames.filter((_, i) => results[i] !== null);
				return channels.length > 0 ? channels : ['stable'];
			}
			const registryResult = getRegistry('rust');
			if (registryResult.isErr()) return [];
			// Try both hyphen and underscore variants for registry lookup
			for (const variant of crateNameVariants(name)) {
				const versions = await registryResult.value.listVersions(variant, limit);
				if (versions.length > 0) return versions;
			}
			return [];
		},

		async resolveVersion(name: string, version: string): Promise<string> {
			if (version === 'latest') {
				const registry = getRegistry('rust');
				if (registry.isOk()) {
					for (const variant of crateNameVariants(name)) {
						const versions = await registry.value.listVersions(variant, 1);
						if (versions.length > 0) return versions[0];
					}
				}
				return version;
			}
			// Resolve Rust channel aliases (stable/beta/nightly) for std crates
			const resolved = await resolveStdVersion(env.CRATE_GRAPHS, name, version);
			return resolved ?? version;
		},

	};
}

/** Build-time entry point — imported via the `$provider` alias (see vite.config.js). */
export function createProvider(event: RequestEvent): DataProvider {
	const env = (event.platform as { env: AppEnv }).env;
	return createCloudflareProvider(env, event);
}

/** Handle WebSocket upgrade by proxying to the CrateRegistry Durable Object. */
export function handleWsUpgrade(event: RequestEvent): Response | Promise<Response> {
	const env = (event.platform as { env: AppEnv }).env;
	const stub = env.CRATE_REGISTRY.get(env.CRATE_REGISTRY.idFromName('global'));
	return stub.fetch(event.request);
}
